basePath: /
definitions:
  fhub.File:
    properties:
      file_date:
        type: string
      file_id:
        type: integer
      file_name:
        type: string
      file_path:
        type: string
      file_size:
        type: integer
    required:
      - file_name
      - file_path
    type: object
  fhub.Folder:
    properties:
      folder_date:
        type: string
      folder_name:
        type: string
      id:
        type: integer
    required:
      - folder_name
    type: object
  fhub.UpdateFileInput:
    properties:
      file_name:
        type: string
      file_path:
        type: string
    type: object
  fhub.UpdateFolderInput:
    properties:
      folder_name:
        description: if empty - got nil
        type: string
    type: object
  fhub.User:
    properties:
      password:
        type: string
      username:
        type: string
    required:
      - password
      - username
    type: object
  handler.errorResponse:
    properties:
      message:
        type: string
    type: object
  handler.getAllFoldersResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/fhub.Folder'
        type: array
    type: object
  handler.signInInput:
    properties:
      password:
        type: string
      username:
        type: string
    required:
      - password
      - username
    type: object
  handler.statusResponse:
    properties:
      status:
        type: string
    type: object
host: localhost:8080
info:
  contact: { }
  description: API Server for Files Managing Application
  title: File-Hub API
  version: "1.0"
paths:
  /api/files/{file_id}:
    delete:
      consumes:
        - application/json
      description: delete file
      operationId: delete-file
      parameters:
        - description: file id
          in: path
          name: file_id
          required: true
          type: integer
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.statusResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      security:
        - ApiKeyAuth: [ ]
      summary: Delete file
      tags:
        - files
    get:
      consumes:
        - application/json
      description: get file by id
      operationId: get-file-by-id
      parameters:
        - description: file id
          in: path
          name: file_id
          required: true
          type: integer
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/fhub.File'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      security:
        - ApiKeyAuth: [ ]
      summary: Get file by id
      tags:
        - files
    put:
      consumes:
        - application/json
      description: update file
      operationId: update-file
      parameters:
        - description: file id
          in: path
          name: file_id
          required: true
          type: integer
        - description: file info
          in: body
          name: input
          required: true
          schema:
            $ref: '#/definitions/fhub.UpdateFileInput'
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.statusResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      security:
        - ApiKeyAuth: [ ]
      summary: Update file
      tags:
        - files
  /api/folders:
    get:
      consumes:
        - application/json
      description: get all folders
      operationId: get-all-folders
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.getAllFoldersResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      security:
        - ApiKeyAuth: [ ]
      summary: Get all folders
      tags:
        - folders
    post:
      consumes:
        - application/json
      description: create folder
      operationId: create-folder
      parameters:
        - description: folder info
          in: body
          name: input
          required: true
          schema:
            $ref: '#/definitions/fhub.Folder'
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      security:
        - ApiKeyAuth: [ ]
      summary: Create folder
      tags:
        - folders
  /api/folders/{folder_id}:
    delete:
      consumes:
        - application/json
      description: delete folder
      operationId: delete-folder
      parameters:
        - description: folder id
          in: path
          name: folder_id
          required: true
          type: integer
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.statusResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      security:
        - ApiKeyAuth: [ ]
      summary: Delete folder
      tags:
        - folders
    get:
      consumes:
        - application/json
      description: get folder by id
      operationId: get-folder-by-id
      parameters:
        - description: folder id
          in: path
          name: folder_id
          required: true
          type: integer
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/fhub.Folder'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      security:
        - ApiKeyAuth: [ ]
      summary: Get folder by id
      tags:
        - folders
    put:
      consumes:
        - application/json
      description: update folder
      operationId: update-folder
      parameters:
        - description: folder id
          in: path
          name: folder_id
          required: true
          type: integer
        - description: folder info
          in: body
          name: input
          required: true
          schema:
            $ref: '#/definitions/fhub.UpdateFolderInput'
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.statusResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      security:
        - ApiKeyAuth: [ ]
      summary: Update folder
      tags:
        - folders
  /api/folders/{folder_id}/files:
    get:
      consumes:
        - application/json
      description: get all files
      operationId: get-all-files
      parameters:
        - description: folder id
          in: path
          name: folder_id
          required: true
          type: integer
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/fhub.File'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      security:
        - ApiKeyAuth: [ ]
      summary: Get all files
      tags:
        - files
    post:
      consumes:
        - application/json
      description: create file
      operationId: create-file
      parameters:
        - description: folder id
          in: path
          name: folder_id
          required: true
          type: integer
        - description: file info
          in: body
          name: input
          required: true
          schema:
            $ref: '#/definitions/fhub.File'
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      security:
        - ApiKeyAuth: [ ]
      summary: Create file
      tags:
        - files
  /auth/sign-in:
    post:
      consumes:
        - application/json
      description: login
      operationId: login
      parameters:
        - description: credentials
          in: body
          name: input
          required: true
          schema:
            $ref: '#/definitions/handler.signInInput'
      produces:
        - application/json
      responses:
        "200":
          description: token
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: SignIn
      tags:
        - auth
  /auth/sign-up:
    post:
      consumes:
        - application/json
      description: create account
      operationId: create-account
      parameters:
        - description: account info
          in: body
          name: input
          required: true
          schema:
            $ref: '#/definitions/fhub.User'
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: SignUp
      tags:
        - auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
